from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import io


def generate_pdf(result, confidence, risk_score, risk_level,
                 info, warnings, explanation):

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b><font size=20>🛡️ JobShieldAI Security Report</font></b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(
        f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
        styles["Normal"]
    ))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Prediction:</b> {result}", styles["Heading2"]))
    story.append(Paragraph(f"<b>Confidence:</b> {confidence:.2f}%", styles["Normal"]))
    story.append(Paragraph(f"<b>Risk Score:</b> {risk_score}/100 ({risk_level})", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Job Information</b>", styles["Heading2"]))

    for key, value in info.items():
        story.append(
            Paragraph(f"<b>{key}:</b> {value}", styles["Normal"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Scam Indicators</b>", styles["Heading2"]))

    for warning in warnings:
        story.append(
            Paragraph(f"• {warning}", styles["Normal"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>AI Explanation</b>", styles["Heading2"]))

    story.append(
        Paragraph(explanation.replace("\n", "<br/>"), styles["Normal"])
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "<b>Generated by JobShieldAI</b><br/>"
            "AI-Powered Fake Job Detection System",
            styles["Italic"]
        )
    )

    doc.build(story)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf